# Generated by Django 6.0.7 on 2026-07-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_de_processos_capro', '0006_alter_controledeprocessosmodel_custos_indiretos_and_more'),
        ('entidade', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sigla', models.CharField(max_length=20)),
                ('pste', models.BooleanField()),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='planilha_entidade', to='entidade.entidademodel')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilha_executor', to='pessoas.pessoamodel')),
                ('processo_sei', models.OneToOneField(max_length=17, on_delete=django.db.models.deletion.CASCADE, related_name='planilha_processo_sei', to='controle_de_processos_capro.controledeprocessosmodel', to_field='processo_sei')),
                ('relator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='planilha_relator', to='pessoas.pessoamodel')),
                ('substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planilha_substituto', to='pessoas.pessoamodel')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilha_supervisor', to='pessoas.pessoamodel')),
            ],
            options={
                'verbose_name': 'Planilha',
                'verbose_name_plural': 'Planilhas',
                'db_table': 'Planilha',
            },
        ),
    ]
