# Generated by Django 6.0.7 on 2026-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0001_initial'),
        ('planilha_bianca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilhamodel',
            name='participes',
            field=models.ManyToManyField(to='entidade.entidademodel'),
        ),
    ]
