# Generated by Django 6.0.7 on 2026-07-30 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrangencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj_cpf', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Entidade Parceira',
                'verbose_name_plural': 'Entidades Parceiras',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Onu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='ProcessoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo_limpo', models.CharField(db_index=True, help_text='Apenas números para busca rápida ex: 23106092037202530', max_length=50, unique=True)),
                ('numero_convenio', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('participes_texto', models.TextField(blank=True, help_text='Texto bruto de partícipes se necessário', null=True)),
                ('tipo_instrumento', models.CharField(choices=[('Convênio', 'Convênio'), ('Contrato', 'Contrato'), ('Acordo de Cooperação', 'Acordo de Cooperação'), ('Termo de Compromisso', 'Termo de Compromisso'), ('Termo de Execução Descentralizada', 'Termo de Execução Descentralizada'), ('Termo de Outorga', 'Termo de Outorga')])),
                ('esfera_administrativa', models.CharField(choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal'), ('Iniciativa Privada', 'Iniciativa Privada'), ('Internacional', 'Internacional')])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('custos_indiretos', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('dt_inicio', models.DateField(blank=True, db_index=True, null=True)),
                ('dt_termino', models.DateField(blank=True, db_index=True, null=True)),
                ('dt_assinatura', models.DateField(blank=True, null=True)),
                ('forma_aprovacao', models.CharField(blank=True, max_length=150, null=True)),
                ('pste', models.BooleanField(default=False)),
                ('coordenado_por_mulheres', models.BooleanField(default=False)),
                ('abrangencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.abrangencia')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to='processos.pessoa')),
                ('entidade_parceira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.entidadeparceira')),
                ('modalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.modalidade')),
                ('natureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.natureza')),
                ('relator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_relatados', to='processos.pessoa')),
                ('substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_substituidos', to='processos.pessoa')),
                ('supervisor_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_supervisionados', to='processos.pessoa')),
                ('unidade_interessada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_interessados', to='processos.unidade')),
            ],
            options={
                'verbose_name': 'Processo / Projeto',
                'verbose_name_plural': 'Processos / Projetos',
            },
        ),
        migrations.CreateModel(
            name='ItemPlanoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='processos.processoprojeto')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.tipodespesa')),
            ],
            options={
                'verbose_name': 'Item do Plano de Despesa',
                'verbose_name_plural': 'Itens do Plano de Despesas',
            },
        ),
    ]
