# Generated by Django 6.0.7 on 2026-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['sigla'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RenameField(
            model_name='processoprojeto',
            old_name='numero_processo_limpo',
            new_name='processo',
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='unidade_interessada',
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='modalidade',
            field=models.ManyToManyField(related_name='processos_modalidade', to='processos.modalidade'),
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='unidade_interessada',
            field=models.ManyToManyField(related_name='projetos_unidade_interessada', to='processos.unidade'),
        ),
    ]
