# Generated by Django 6.0.7 on 2026-07-30 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoamodel_matricula'),
        ('processos', '0002_alter_modalidade_options_alter_unidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoprojeto',
            name='substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_substituidos', to='pessoas.pessoamodel'),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='supervisor_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_supervisionados', to='pessoas.pessoamodel'),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_coordenados', to='pessoas.pessoamodel'),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_relatados', to='pessoas.pessoamodel'),
        ),
        migrations.AlterModelOptions(
            name='abrangencia',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='entidadeparceira',
            options={'ordering': ['sigla'], 'verbose_name': 'Entidade Parceira', 'verbose_name_plural': 'Entidades Parceiras'},
        ),
        migrations.AlterModelOptions(
            name='natureza',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='processoprojeto',
            options={'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Despesa', 'verbose_name_plural': 'Tipos de Despesas'},
        ),
        migrations.AddField(
            model_name='entidadeparceira',
            name='publico_privado',
            field=models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidadeparceira',
            name='sigla',
            field=models.CharField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidadeparceira',
            name='cnpj_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='esfera_administrativa',
            field=models.CharField(choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal'), ('Iniciativa Privada', 'Iniciativa Privada'), ('Internacional', 'Internacional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='modalidade',
            field=models.ManyToManyField(related_name='processos', to='processos.modalidade'),
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='natureza',
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='processo',
            field=models.CharField(db_index=True, help_text='Apenas números para busca rápida ex: 23106092037202530', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O processo deve conter apenas números.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='tipo_instrumento',
            field=models.CharField(choices=[('Convênio', 'Convênio'), ('Contrato', 'Contrato'), ('Acordo de Cooperação', 'Acordo de Cooperação'), ('Termo de Compromisso', 'Termo de Compromisso'), ('Termo de Execução Descentralizada', 'Termo de Execução Descentralizada'), ('Termo de Outorga', 'Termo de Outorga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='unidade_interessada',
            field=models.ManyToManyField(related_name='projetos', to='processos.unidade'),
        ),
        migrations.AddIndex(
            model_name='processoprojeto',
            index=models.Index(fields=['dt_inicio'], name='processos_p_dt_inic_746781_idx'),
        ),
        migrations.AddIndex(
            model_name='processoprojeto',
            index=models.Index(fields=['dt_termino'], name='processos_p_dt_term_5f2113_idx'),
        ),
        migrations.AddIndex(
            model_name='processoprojeto',
            index=models.Index(fields=['processo'], name='processos_p_process_aae71f_idx'),
        ),
        migrations.AddIndex(
            model_name='processoprojeto',
            index=models.Index(fields=['entidade_parceira'], name='processos_p_entidad_03c071_idx'),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='natureza',
            field=models.ManyToManyField(blank=True, related_name='processos', to='processos.natureza'),
        ),
    ]
