# Generated by Django 6.0.7 on 2026-07-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_alter_processoprojeto_substituto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modalidade',
            new_name='ModalidadeModel',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='Processos_dt_inic_d592a7_idx',
            old_name='processos_p_dt_inic_746781_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='Processos_dt_term_7d1d73_idx',
            old_name='processos_p_dt_term_5f2113_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='Processos_process_4ad998_idx',
            old_name='processos_p_process_aae71f_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='Processos_entidad_338473_idx',
            old_name='processos_p_entidad_03c071_idx',
        ),
        migrations.AlterModelTable(
            name='abrangencia',
            table='Abrangencia',
        ),
        migrations.AlterModelTable(
            name='itemplanodespesa',
            table='ItemPlanoDespesa',
        ),
        migrations.AlterModelTable(
            name='modalidademodel',
            table='Modalidade',
        ),
        migrations.AlterModelTable(
            name='natureza',
            table='Natureza',
        ),
        migrations.AlterModelTable(
            name='processoprojeto',
            table='Processos',
        ),
        migrations.AlterModelTable(
            name='tipodespesa',
            table='TipoDespesa',
        ),
    ]
