# Generated by Django 6.0.7 on 2026-07-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_rename_modalidade_modalidademodel_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='processos_p_dt_inic_746781_idx',
            old_name='Processos_dt_inic_d592a7_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='processos_p_dt_term_5f2113_idx',
            old_name='Processos_dt_term_7d1d73_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='processos_p_process_aae71f_idx',
            old_name='Processos_process_4ad998_idx',
        ),
        migrations.RenameIndex(
            model_name='processoprojeto',
            new_name='processos_p_entidad_03c071_idx',
            old_name='Processos_entidad_338473_idx',
        ),
        migrations.AlterModelTable(
            name='abrangencia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='itemplanodespesa',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modalidademodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='natureza',
            table=None,
        ),
        migrations.AlterModelTable(
            name='processoprojeto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipodespesa',
            table=None,
        ),
    ]
