# Generated by Django 6.0.7 on 2026-07-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_rename_processos_dt_inic_d592a7_idx_processos_p_dt_inic_746781_idx_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModalidadeModel',
            new_name='Modalidade',
        ),
    ]
