# Generated by Django 6.0.7 on 2026-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_rename_modalidademodel_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoprojeto',
            name='nome_do_processo',
            field=models.CharField(default=1, max_length=255,blank=False, null=False),
            preserve_default=False,
        ),
    ]
