# Generated by Django 6.0.7 on 2026-07-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_processoprojeto_nome_do_processo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onu',
        ),
    ]
