# Generated by Django 6.0.7 on 2026-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_delete_onu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoprojeto',
            name='nome_do_processo',
            field=models.CharField(max_length=255),
        ),
    ]
