# Generated by Django 6.0.7 on 2026-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_alter_processoprojeto_nome_do_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoprojeto',
            name='ods_onu',
            field=models.CharField(blank=True, choices=[('1', '1. Erradicação da Pobreza'), ('2', '2. Fome Zero e Agricultura Sustentável'), ('3', '3. Saúde e Bem-Estar'), ('4', '4. Educação de Qualidade'), ('5', '5. Igualdade de Gênero'), ('6', '6. Água Potável e Saneamento'), ('7', '7. Energia Limpa e Acessível'), ('8', '8. Trabalho Decente e Crescimento Econômico'), ('9', '9. Indústria, Inovação e Infraestrutura'), ('10', '10. Redução das Desigualdades'), ('11', '11. Cidades e Comunidades Sustentáveis'), ('12', '12. Consumo e Produção Responsáveis'), ('13', '13. Ação Contra a Mudança Global do Clima'), ('14', '14. Vida na Água'), ('15', '15. Vida Terrestre'), ('16', '16. Paz, Justiça e Instituições Eficazes'), ('17', '17. Parcerias e Meios de Implementação')], max_length=50),
        ),
    ]
