# Generated by Django 6.0.7 on 2026-07-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_processoprojeto_ods_onu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoprojeto',
            name='coordenado_por_mulheres',
        ),
    ]
