# Generated by Django 6.0.7 on 2026-07-31 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_remove_processoprojeto_coordenado_por_mulheres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='participes_texto',
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='processo',
            field=models.CharField(db_index=True, help_text='Apenas números para busca rápida ex: 2310600000000001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O processo deve conter apenas números.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='participes',
            field=models.ManyToManyField(blank=True, related_name='processos', to='processos.participesmodel'),
        ),
    ]
