# Generated by Django 6.0.7 on 2026-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_participesmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participesmodel',
            options={'ordering': ['sigla'], 'verbose_name': 'Participe', 'verbose_name_plural': 'Participes'},
        ),
        migrations.AlterField(
            model_name='participesmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
