# Generated by Django 6.0.7 on 2026-08-04 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_alter_participesmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermosAdtivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField()),
                ('dt_termino', models.DateField(blank=True, db_index=True, null=True)),
                ('dt_assinatura', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25)),
            ],
            options={
                'verbose_name': 'Termo de Adtivos',
                'verbose_name_plural': 'Termos de Adtivos',
                'ordering': ['dt_termino'],
            },
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='forma_aprovacao',
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='pste',
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='valor_inicial',
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='termo_adtivo',
            field=models.ManyToManyField(related_name='termos_adtivos', to='processos.termosadtivos'),
        ),
    ]
