# Generated by Django 6.0.7 on 2026-08-05 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrangencia',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abrangencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entidadeparceira',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entidadeparceira',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemplanodespesa',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemplanodespesa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='natureza',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='natureza',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participesmodel',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participesmodel',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='termo_adtivo',
            field=models.ManyToManyField(blank=True, related_name='termos_adtivos', to='processos.termosadtivos'),
        ),
        migrations.AlterField(
            model_name='termosadtivos',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termosadtivos',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termosadtivos',
            name='termo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipodespesa',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True)),
                ('origem_registro', models.CharField(choices=[('manual', 'Cadastro manual'), ('importacao', 'Importação'), ('integracao', 'Integração')], default='manual', max_length=20)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de instrumento',
                'verbose_name_plural': 'Tipos de instrumento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='tipo_instrumento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processoprojeto',
            name='tipo_instrumento_novo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='processos.tipoinstrumento'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                setattr(processo, 'tipo_instrumento_novo_id', apps.get_model('processos', 'TipoInstrumento').objects.get_or_create(nome=processo.tipo_instrumento)[0].pk) or processo.save(update_fields=['tipo_instrumento_novo'])
                for processo in apps.get_model('processos', 'ProcessoProjeto').objects.exclude(tipo_instrumento__isnull=True).exclude(tipo_instrumento='')
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='processoprojeto',
            name='tipo_instrumento',
        ),
        migrations.RenameField(
            model_name='processoprojeto',
            old_name='tipo_instrumento_novo',
            new_name='tipo_instrumento',
        ),
        migrations.AlterField(
            model_name='processoprojeto',
            name='tipo_instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processos.tipoinstrumento'),
        ),
    ]
