# Generated by Django 6.0.7 on 2026-08-06 15:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_alter_pessoamodel_atualizado_por_and_more'),
        ('processos', '0018_remover_relacao_antiga_termo_aditivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processoprojeto',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='processoprojeto',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='processos_p_search__b42ea1_gin'),
        ),
    ]
