# Generated by Django 6.0.7 on 2026-08-06 19:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_processoprojeto_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoprojeto',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25),
        ),
    ]
