# Generated by Django 6.0.7 on 2026-08-06 20:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_processoprojeto_valor_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoprojeto',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=25), max_digits=25),
        ),
    ]
