# Generated by Django 6.0.7 on 2026-07-29 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pessoas.pessoamodel')),
            ],
            options={
                'db_table': 'Coordenador',
            },
        ),
        migrations.CreateModel(
            name='ControleDeProcessosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('processo_sei', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='O processo deve conter exatamente 17 dígitos.', regex='^\\d{17}$')])),
                ('modalidade', models.IntegerField(choices=[(1, 'E'), (2, 'F'), (3, 'G')], max_length=50)),
                ('natureza', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], max_length=50)),
                ('abrangencia', models.IntegerField(choices=[(1, ''), (2, ''), (3, '')], max_length=50)),
                ('forma_de_aprovacao', models.IntegerField(choices=[(1, ''), (2, ''), (3, '')], max_length=50)),
                ('custos_indiretos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('esfera_administrativa', models.IntegerField(choices=[(1, 'Federal'), (2, 'Estadual'), (3, 'Municipal'), (4, 'Iniciativa Privada'), (5, 'Internacional')])),
                ('ementa', models.TextField(max_length=600)),
                ('mes_da_aprovacao', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoamodel')),
            ],
            options={
                'db_table': 'ControleDeProcessos',
                'indexes': [models.Index(fields=['processo_sei'], name='ControleDeP_process_18f7c2_idx'), models.Index(fields=['coordenador'], name='ControleDeP_coorden_ef3327_idx'), models.Index(fields=['mes_da_aprovacao'], name='ControleDeP_mes_da__0bb1ff_idx'), models.Index(fields=['esfera_administrativa'], name='ControleDeP_esfera__dd28b1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('custos_indiretos__gte', 0)), name='custos_indiretos_positivo')],
            },
        ),
    ]
