# Generated by Django 6.0.7 on 2026-07-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='ControleDeProcessosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('processo_sei', models.CharField(max_length=17)),
                ('modalidade', models.CharField(choices=[('', ''), ('', ''), ('', '')])),
                ('natureza', models.CharField(choices=[('', ''), ('', ''), ('', '')])),
                ('abrangencia', models.CharField(choices=[('', ''), ('', ''), ('', '')])),
                ('forma_de_aprovacao', models.CharField(choices=[('', ''), ('', ''), ('', '')])),
                ('custos_indiretos', models.FloatField()),
                ('esfera_administrativa', models.IntegerField(choices=[(1, 'Federal'), (2, 'Estadual'), (3, 'Municipal'), (4, 'Iniciativa privada'), (5, 'Internacional')])),
                ('ementa', models.TextField(max_length=600)),
                ('mes_da_aprovacao', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_de_processos_capro.coordenador')),
            ],
        ),
    ]
