# Generated by Django 6.0.7 on 2026-07-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='controledeprocessosmodel',
            table='ControleDeProcessos',
        ),
    ]
