# Generated by Django 6.0.7 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
