# Generated by Django 6.0.7 on 2026-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0002_alter_controledeprocessosmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='matricula',
            field=models.CharField(default=1, max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='abrangencia',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='forma_de_aprovacao',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='modalidade',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='natureza',
            field=models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=50),
        ),
    ]
