# Generated by Django 6.0.7 on 2026-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0002_alter_controledeprocessosmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='abrangencia',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, '')]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='forma_de_aprovacao',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, '')]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='modalidade',
            field=models.IntegerField(choices=[(1, 'E'), (2, 'F'), (3, 'G')]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='natureza',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')]),
        ),
        migrations.DeleteModel(
            name='CoordenadorModel',
        ),
    ]
