# Generated by Django 6.0.7 on 2026-07-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0003_coordenador_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordenador',
            table='Coordenador',
        ),
    ]
