# Generated by Django 6.0.7 on 2026-07-29 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0003_alter_controledeprocessosmodel_abrangencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controledeprocessosmodel',
            name='valor_do_contrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='custos_indiretos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
