# Generated by Django 6.0.7 on 2026-07-28 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0004_alter_coordenador_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordenador',
            new_name='CoordenadorModel',
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='abrangencia',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='custos_indiretos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='esfera_administrativa',
            field=models.IntegerField(choices=[(1, 'Federal'), (2, 'Estadual'), (3, 'Municipal'), (4, 'Iniciativa Privada'), (5, 'Internacional')]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='forma_de_aprovacao',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='modalidade',
            field=models.IntegerField(choices=[(1, 'E'), (2, 'F'), (3, 'G')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='natureza',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], max_length=50),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='processo_sei',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='O processo deve conter exatamente 17 dígitos.', regex='^\\d{17}$')]),
        ),
        migrations.AddIndex(
            model_name='controledeprocessosmodel',
            index=models.Index(fields=['processo_sei'], name='ControleDeP_process_18f7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='controledeprocessosmodel',
            index=models.Index(fields=['coordenador'], name='ControleDeP_coorden_ef3327_idx'),
        ),
        migrations.AddIndex(
            model_name='controledeprocessosmodel',
            index=models.Index(fields=['mes_da_aprovacao'], name='ControleDeP_mes_da__0bb1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='controledeprocessosmodel',
            index=models.Index(fields=['esfera_administrativa'], name='ControleDeP_esfera__dd28b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='controledeprocessosmodel',
            constraint=models.CheckConstraint(condition=models.Q(('custos_indiretos__gte', 0)), name='custos_indiretos_positivo'),
        ),
    ]
