# Generated by Django 6.0.7 on 2026-07-29 18:04

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0004_controledeprocessosmodel_valor_do_contrato_and_more'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='controledeprocessosmodel',
            name='ControleDeP_mes_da__0bb1ff_idx',
        ),
        migrations.AddField(
            model_name='controledeprocessosmodel',
            name='data_da_aprovacao',
            field=models.DateField(default=datetime.today),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='controledeprocessosmodel',
            index=models.Index(fields=['data_da_aprovacao'], name='ControleDeP_data_da_f79e86_idx'),
        ),
        migrations.RemoveField(
            model_name='controledeprocessosmodel',
            name='mes_da_aprovacao',
        ),
    ]
