# Generated by Django 6.0.7 on 2026-07-29 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_de_processos_capro', '0005_remove_controledeprocessosmodel_controledep_mes_da__0bb1ff_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='custos_indiretos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='controledeprocessosmodel',
            name='valor_do_contrato',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
