# Generated by Django 6.0.7 on 2026-07-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoamodel_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoamodel',
            options={'ordering': ['nome']},
        ),
    ]
