# Generated by Django 6.0.7 on 2026-08-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_alter_pessoamodel_atualizado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeDeLotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=60, null=True)),
                ('nome', models.CharField(max_length=180)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoamodel',
            name='sexo',
        ),
        migrations.AddField(
            model_name='pessoamodel',
            name='unidade_de_lotacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoas.unidadedelotacao'),
        ),
    ]
