# Generated by Django 6.0.7 on 2026-08-06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pessoas', '0006_unidadedelotacao_remove_pessoamodel_sexo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadedelotacao',
            options={'ordering': ['sigla', 'nome']},
        ),
    ]
